/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LeCodeViewer: typeof import('@lee/ui')['CodeViewer']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NIconWrapper: typeof import('naive-ui')['NIconWrapper']
    NInput: typeof import('naive-ui')['NInput']
    NLi: typeof import('naive-ui')['NLi']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NTable: typeof import('naive-ui')['NTable']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NUl: typeof import('naive-ui')['NUl']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const LeCodeViewer: typeof import('@lee/ui')['CodeViewer']
  const NAlert: typeof import('naive-ui')['NAlert']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NCheckbox: typeof import('naive-ui')['NCheckbox']
  const NCollapse: typeof import('naive-ui')['NCollapse']
  const NCollapseItem: typeof import('naive-ui')['NCollapseItem']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDescriptions: typeof import('naive-ui')['NDescriptions']
  const NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
  const NDialogProvider: typeof import('naive-ui')['NDialogProvider']
  const NDivider: typeof import('naive-ui')['NDivider']
  const NDropdown: typeof import('naive-ui')['NDropdown']
  const NEmpty: typeof import('naive-ui')['NEmpty']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NGrid: typeof import('naive-ui')['NGrid']
  const NGridItem: typeof import('naive-ui')['NGridItem']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NIconWrapper: typeof import('naive-ui')['NIconWrapper']
  const NInput: typeof import('naive-ui')['NInput']
  const NLi: typeof import('naive-ui')['NLi']
  const NMenu: typeof import('naive-ui')['NMenu']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NSpace: typeof import('naive-ui')['NSpace']
  const NStatistic: typeof import('naive-ui')['NStatistic']
  const NTable: typeof import('naive-ui')['NTable']
  const NTabPane: typeof import('naive-ui')['NTabPane']
  const NTabs: typeof import('naive-ui')['NTabs']
  const NTag: typeof import('naive-ui')['NTag']
  const NText: typeof import('naive-ui')['NText']
  const NUl: typeof import('naive-ui')['NUl']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}